name: github_api
description: Github Api
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  secure_storage:
    path: ../secure_storage

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
