include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  exclude:
    - lib/src/models/**.g.dart    